server.port=8082
spring.application.name=pipeline-service

spring.datasource.url=jdbc:mysql://mysql-pipeline:3306/pipeline_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Jenkins Config (mock mode if not set)
jenkins.url=http://jenkins:8080
jenkins.username=admin
jenkins.token=admin
jenkins.mock-mode=true

# Other services
alert.service.url=http://alert-service:8083
retry.service.url=http://retry-service:8084

# Scheduler - poll every 60 seconds
scheduler.poll.interval=60000

management.endpoints.web.exposure.include=health,prometheus,info,metrics
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true
